Repository AY2122S1-CS2113T-F12-4/tp, pull requests merged in 2021-10, with the labels that each got.

#33 Edit userguide.md to include expected outputs and table of contents
  docs/UserGuide.md
  src/main/java/seedu/duke/Entry.java
  src/main/java/seedu/duke/Parser.java
Labels: type.Enhancement

#44 able to write to CSV file
  src/main/java/seedu/duke/Entry.java
  src/main/java/seedu/duke/MemberStorage.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/member/MemberList.java
Labels: priority.Medium

#54 Edit README.md
  docs/README.md
Labels: type.Enhancement, priority.Medium

#51 finished loading
  src/main/java/seedu/duke/MemberStorage.java
  src/main/java/seedu/duke/member/Member.java
Labels: type.Story, priority.High

#59 Edit and sort JUnit tests, fix indexing issues in MemberList.java
  DukeMembers.csv
  README.md
  docs/UserGuide.md
  src/main/java/seedu/duke/Entry.java
  src/main/java/seedu/duke/MemberStorage.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/member/Member.java
  src/main/java/seedu/duke/member/MemberList.java
  src/main/java/seedu/duke/training/TrainingList.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/member/MemberListTest.java
  src/test/java/seedu/duke/training/TrainingListTest.java
Labels: type.Enhancement

#60 Edit and sort JUnit tests, fix MemberList indexing issue
  DukeMembers.csv
  src/main/java/seedu/duke/MemberStorage.java
  src/main/java/seedu/duke/member/MemberList.java
  src/main/java/seedu/duke/training/TrainingList.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/member/MemberListTest.java
  src/test/java/seedu/duke/training/TrainingListTest.java
Labels: type.Enhancement

#62 Fix more codingstyle errors
  src/main/java/seedu/duke/Entry.java
  src/main/java/seedu/duke/MemberStorage.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/attendance/Attendance.java
  src/main/java/seedu/duke/member/Member.java
  src/main/java/seedu/duke/member/MemberList.java
  src/test/java/seedu/duke/training/TrainingListTest.java
Labels: type.Enhancement

#69 Handle exceptions for training class
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/training/TrainingList.java
Labels: type.Bug

#75 Fix file insertion for edit member function
  README.md
  _config.yml
  docs/README.md
  docs/UserGuide.md
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Entry.java
  src/main/java/seedu/duke/Keyword.java
  src/main/java/seedu/duke/MemberStorage.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/member/MemberList.java
  src/main/java/seedu/duke/member/exception/InvalidMemberException.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/member/MemberListTest.java
Labels: type.Bug

#82 Edited attendance information & updated UG accordingly to "student name | training name | attendance status (present OR late)
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/attendance/Attendance.java
  src/main/java/seedu/duke/attendance/AttendanceList.java
  src/main/java/seedu/duke/member/Member.java
Labels: type.Enhancement
